export const keyboardKeys = [
  {
    code: 'Backquote',
    en: '`',
    ru: 'ё',
    enShift: '~',
    ruShift: 'Ё',
    enCaps: '~',
    ruCaps: 'Ё',
  },
  {
    code: 'Digit1',
    en: '1',
    ru: '1',
    enShift: '!',
    ruShift: '!',
    enCaps: '1',
    ruCaps: '1',
  },
  {
    code: 'Digit2',
    en: '2',
    ru: '2',
    enShift: '@',
    ruShift: '"',
    enCaps: '2',
    ruCaps: '2',
  },
  {
    code: 'Digit3',
    en: '3',
    ru: '3',
    enShift: '#',
    ruShift: '№',
    enCaps: '3',
    ruCaps: '3',
  },
  {
    code: 'Digit4',
    en: '4',
    ru: '4',
    enShift: '$',
    ruShift: ';',
    enCaps: '4',
    ruCaps: '4',
  },
  {
    code: 'Digit5',
    en: '5',
    ru: '5',
    enShift: '%',
    ruShift: '%',
    enCaps: '5',
    ruCaps: '5',
  },
  {
    code: 'Digit6',
    en: '6',
    ru: '6',
    enShift: '^',
    ruShift: ':',
    enCaps: '6',
    ruCaps: '6',
  },
  {
    code: 'Digit7',
    en: '7',
    ru: '7',
    enShift: '&',
    ruShift: '?',
    enCaps: '7',
    ruCaps: '7',
  },
  {
    code: 'Digit8',
    en: '8',
    ru: '8',
    enShift: '*',
    ruShift: '*',
    enCaps: '8',
    ruCaps: '8',
  },
  {
    code: 'Digit9',
    en: '9',
    ru: '9',
    enShift: '(',
    ruShift: '(',
    enCaps: '9',
    ruCaps: '9',
  },
  {
    code: 'Digit0',
    en: '0',
    ru: '0',
    enShift: ')',
    ruShift: ')',
    enCaps: '0',
    ruCaps: '0',
  },
  {
    code: 'Minus',
    en: '-',
    ru: '-',
    enShift: '_',
    ruShift: '_',
    enCaps: '-',
    ruCaps: '-',
  },
  {
    code: 'Equal',
    en: '=',
    ru: '=',
    enShift: '+',
    ruShift: '+',
    enCaps: '=',
    ruCaps: '=',
  },
  {
    code: 'Backspace',
    en: 'Backspace',
    ru: 'Backspace',
    enShift: 'Backspace',
    ruShift: 'Backspace',
    enCaps: 'Backspace',
    ruCaps: 'Backspace',
  },
  {
    code: 'Tab',
    en: 'Tab',
    ru: 'Tab',
    enShift: 'Tab',
    ruShift: 'Tab',
    enCaps: 'Tab',
    ruCaps: 'Tab',
  },
  {
    code: 'KeyQ',
    en: 'q',
    ru: 'й',
    enShift: 'Q',
    ruShift: 'Й',
    enCaps: 'Q',
    ruCaps: 'Й',
  },
  {
    code: 'KeyW',
    en: 'w',
    ru: 'ц',
    enShift: 'W',
    ruShift: 'Ц',
    enCaps: 'W',
    ruCaps: 'Ц',
  },
  {
    code: 'KeyE',
    en: 'e',
    ru: 'у',
    enShift: 'E',
    ruShift: 'У',
    enCaps: 'E',
    ruCaps: 'У',
  },
  {
    code: 'KeyR',
    en: 'r',
    ru: 'к',
    enShift: 'R',
    ruShift: 'К',
    enCaps: 'R',
    ruCaps: 'К',
  },
  {
    code: 'KeyT',
    en: 't',
    ru: 'е',
    enShift: 'T',
    ruShift: 'Е',
    enCaps: 'T',
    ruCaps: 'Е',
  },
  {
    code: 'KeyY',
    en: 'y',
    ru: 'н',
    enShift: 'Y',
    ruShift: 'Н',
    enCaps: 'Y',
    ruCaps: 'Н',
  },
  {
    code: 'KeyU',
    en: 'u',
    ru: 'г',
    enShift: 'U',
    ruShift: 'Г',
    enCaps: 'U',
    ruCaps: 'Г',
  },
  {
    code: 'KeyI',
    en: 'i',
    ru: 'ш',
    enShift: 'I',
    ruShift: 'Ш',
    enCaps: 'I',
    ruCaps: 'Ш',
  },
  {
    code: 'KeyO',
    en: 'o',
    ru: 'щ',
    enShift: 'O',
    ruShift: 'Щ',
    enCaps: 'O',
    ruCaps: 'Щ',
  },
  {
    code: 'KeyP',
    en: 'p',
    ru: 'з',
    enShift: 'P',
    ruShift: 'З',
    enCaps: 'P',
    ruCaps: 'З',
  },
  {
    code: 'BracketLeft',
    en: '[',
    ru: 'х',
    enShift: '{',
    ruShift: 'Х',
    enCaps: '[',
    ruCaps: 'Х',
  },
  {
    code: 'BracketRight',
    en: ']',
    ru: 'ъ',
    enShift: '}',
    ruShift: 'Ъ',
    enCaps: ']',
    ruCaps: 'Ъ',
  },
  {
    code: 'Backslash',
    en: '\\',
    ru: '\\',
    enShift: '|',
    ruShift: '/',
    enCaps: '\\',
    ruCaps: '/',
  },
  {
    code: 'Delete',
    en: 'Del',
    ru: 'Del',
    enShift: 'Del',
    ruShift: 'Del',
    enCaps: 'Del',
    ruCaps: 'Del',
  },
  {
    code: 'CapsLock',
    en: 'Caps Lock',
    ru: 'Caps Lock',
    enShift: 'Caps Lock',
    ruShift: 'Caps Lock',
    enCaps: 'Caps Lock',
    ruCaps: 'Caps Lock',
  },
  {
    code: 'KeyA',
    en: 'a',
    ru: 'ф',
    enShift: 'A',
    ruShift: 'Ф',
    enCaps: 'A',
    ruCaps: 'Ф',
  },
  {
    code: 'KeyS',
    en: 's',
    ru: 'ы',
    enShift: 'S',
    ruShift: 'Ы',
    enCaps: 'S',
    ruCaps: 'Ы',
  },
  {
    code: 'KeyD',
    en: 'd',
    ru: 'в',
    enShift: 'D',
    ruShift: 'В',
    enCaps: 'D',
    ruCaps: 'В',
  },
  {
    code: 'KeyF',
    en: 'f',
    ru: 'а',
    enShift: 'F',
    ruShift: 'А',
    enCaps: 'F',
    ruCaps: 'А',
  },
  {
    code: 'KeyG',
    en: 'g',
    ru: 'п',
    enShift: 'G',
    ruShift: 'П',
    enCaps: 'G',
    ruCaps: 'П',
  },
  {
    code: 'KeyH',
    en: 'h',
    ru: 'р',
    enShift: 'H',
    ruShift: 'Р',
    enCaps: 'H',
    ruCaps: 'Р',
  },
  {
    code: 'KeyJ',
    en: 'j',
    ru: 'о',
    enShift: 'J',
    ruShift: 'О',
    enCaps: 'J',
    ruCaps: 'О',
  },
  {
    code: 'KeyK',
    en: 'k',
    ru: 'л',
    enShift: 'K',
    ruShift: 'Л',
    enCaps: 'K',
    ruCaps: 'Л',
  },
  {
    code: 'KeyL',
    en: 'l',
    ru: 'д',
    enShift: 'L',
    ruShift: 'Д',
    enCaps: 'L',
    ruCaps: 'Д',
  },
  {
    code: 'Semicolon',
    en: ';',
    ru: 'ж',
    enShift: ':',
    ruShift: 'Ж',
    enCaps: ';',
    ruCaps: 'Ж',
  },
  {
    code: 'Quote',
    en: "'",
    ru: 'э',
    enShift: '"',
    ruShift: 'Э',
    enCaps: "'",
    ruCaps: 'Э',
  },
  {
    code: 'Enter',
    en: 'Enter',
    ru: 'Enter',
    enShift: 'Enter',
    ruShift: 'Enter',
    enCaps: 'Enter',
    ruCaps: 'Enter',
  },
  {
    code: 'ShiftLeft',
    en: 'Shift',
    ru: 'Shift',
    enShift: 'Shift',
    ruShift: 'Shift',
    enCaps: 'Shift',
    ruCaps: 'Shift',
  },
  {
    code: 'KeyZ',
    en: 'z',
    ru: 'я',
    enShift: 'Z',
    ruShift: 'Я',
    enCaps: 'Z',
    ruCaps: 'Я',
  },
  {
    code: 'KeyX',
    en: 'x',
    ru: 'ч',
    enShift: 'X',
    ruShift: 'Ч',
    enCaps: 'X',
    ruCaps: 'Ч',
  },
  {
    code: 'KeyC',
    en: 'c',
    ru: 'с',
    enShift: 'C',
    ruShift: 'С',
    enCaps: 'C',
    ruCaps: 'С',
  },
  {
    code: 'KeyV',
    en: 'v',
    ru: 'м',
    enShift: 'V',
    ruShift: 'М',
    enCaps: 'V',
    ruCaps: 'М',
  },
  {
    code: 'KeyB',
    en: 'b',
    ru: 'и',
    enShift: 'B',
    ruShift: 'И',
    enCaps: 'B',
    ruCaps: 'И',
  },
  {
    code: 'KeyN',
    en: 'n',
    ru: 'т',
    enShift: 'N',
    ruShift: 'Т',
    enCaps: 'N',
    ruCaps: 'Т',
  },
  {
    code: 'KeyM',
    en: 'm',
    ru: 'ь',
    enShift: 'M',
    ruShift: 'Ь',
    enCaps: 'M',
    ruCaps: 'Ь',
  },
  {
    code: 'Comma',
    en: ',',
    ru: 'б',
    enShift: '<',
    ruShift: 'Б',
    enCaps: ',',
    ruCaps: 'Б',
  },
  {
    code: 'Period',
    en: '.',
    ru: 'ю',
    enShift: '>',
    ruShift: 'Ю',
    enCaps: '.',
    ruCaps: 'Ю',
  },
  {
    code: 'Slash',
    en: '/',
    ru: '.',
    enShift: '?',
    ruShift: ',',
    enCaps: '/',
    ruCaps: '.',
  },
  {
    code: 'ArrowUp',
    en: '⯅',
    ru: '⯅',
    enShift: '⯅',
    ruShift: '⯅',
    enCaps: '⯅',
    ruCaps: '⯅',
  },
  {
    code: 'ShiftRight',
    en: 'Shift',
    ru: 'Shift',
    enShift: 'Shift',
    ruShift: 'Shift',
    enCaps: 'Shift',
    ruCaps: 'Shift',
  },
  {
    code: 'ControlLeft',
    en: 'Ctrl',
    ru: 'Ctrl',
    enShift: 'Ctrl',
    ruShift: 'Ctrl',
    enCaps: 'Ctrl',
    ruCaps: 'Ctrl',
  },
  {
    code: 'MetaLeft',
    en: 'Win',
    ru: 'Win',
    enShift: 'Win',
    ruShift: 'Win',
    enCaps: 'Win',
    ruCaps: 'Win',
  },
  {
    code: 'AltLeft',
    en: 'Alt',
    ru: 'Alt',
    enShift: 'Alt',
    ruShift: 'Alt',
    enCaps: 'Alt',
    ruCaps: 'Alt',
  },
  {
    code: 'Space',
    en: ' ',
    ru: ' ',
    enShift: ' ',
    ruShift: ' ',
    enCaps: ' ',
    ruCaps: ' ',
  },
  {
    code: 'AltRight',
    en: 'Alt',
    ru: 'Alt',
    enShift: 'Alt',
    ruShift: 'Alt',
    enCaps: 'Alt',
    ruCaps: 'Alt',
  },
  {
    code: 'ArrowLeft',
    en: '⯇',
    ru: '⯇',
    enShift: '⯇',
    ruShift: '⯇',
    enCaps: '⯇',
    ruCaps: '⯇',
  },
  {
    code: 'ArrowDown',
    en: '⯆',
    ru: '⯆',
    enShift: '⯆',
    ruShift: '⯆',
    enCaps: '⯆',
    ruCaps: '⯆',
  },
  {
    code: 'ArrowRight',
    en: '⯈',
    ru: '⯈',
    enShift: '⯈',
    ruShift: '⯈',
    enCaps: '⯈',
    ruCaps: '⯈',
  },
  {
    code: 'ControlRight',
    en: 'Ctrl',
    ru: 'Ctrl',
    enShift: 'Ctrl',
    ruShift: 'Ctrl',
    enCaps: 'Ctrl',
    ruCaps: 'Ctrl',
  },
];
